name: Eserve
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission:
  flutter_polyline_points: ^0.2.1
  google_map_polyline:
  google_maps_flutter: 
  page_indicator: ^0.1.3
  firebase_messaging: ^6.0.13
  firebase_auth: 0.16.1
  google_sign_in: ^4.0.1+1
  firebase_storage: ^3.1.5
  cloud_firestore:
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  flutter_map: 0.9.0
  geocoder:
  geolocation:
  image_picker: 
  path_provider: 1.6.10
  timeago: 2.0.17
  cached_network_image: 2.2.0+1
  flutter_icons: ^1.1.0
  time_range_picker: 1.0.1
  fluttertoast: ^4.0.0
  f_datetimerangepicker: ^0.1.3
  flutter_spinkit: "^4.1.2"
  call_number: 0.0.1
  multiselect_formfield: 0.1.3
  location: ^3.0.0
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg:  # help us to use SVG in our app
  provider: ^4.3.1 # for State management

dev_dependencies:
  flutter_test:
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
     - images/haircut.jpg
     - images/da.jpg
     - images/scissor_icon.png
     - images/shave_icon.png
     - images/massage_icon.png
     - images/one.png
     - images/haircut_background.png
     - images/massage_pic.jpg
     - images/salon_shop.png
     - images/shaving_pic.png
     - images/profile_overview.png
     - images/google_logo.png
     - images/creditcards.png
     - images/jazz.jpg 
     - images/eservelog.png 
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
